# Generated by Django 4.1.3 on 2022-11-10 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME_PRODUTO', models.CharField(max_length=30)),
                ('VALOR', models.IntegerField()),
                ('QUANTIDADE_ESTOQUE', models.IntegerField()),
                ('DESCRICAO', models.CharField(max_length=100)),
                ('CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME_CARRINHO', models.CharField(max_length=30)),
                ('QUANTIDADE', models.IntegerField()),
                ('STATUS_CARRINHO', models.CharField(choices=[('Pedido Realizado', 'Pedido Realizado'), ('Pedido Confirmado', 'Pedido Confirmado')], default='Pedido Realizado', max_length=40)),
                ('ID_CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ID_PRODUTO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Produtos.produto')),
            ],
        ),
    ]
