# Generated by Django 4.1.2 on 2022-11-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='ID_CLIENTE',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='ID_PRODUTO',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
