# Generated by Django 4.1.3 on 2022-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='VALOR',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
