# Generated by Django 4.1.2 on 2022-11-01 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Produtos', '0002_remove_carrinho_id_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PEDIDO', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME_CARRINHO', models.CharField(max_length=30)),
                ('QUANTIDADE', models.IntegerField()),
                ('ID_CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ID_PRODUTO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Produtos.produto')),
            ],
        ),
    ]
