# Generated by Django 4.1.3 on 2022-11-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_alter_produto_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='CREATED_BY',
        ),
        migrations.AlterField(
            model_name='produto',
            name='NOME_PRODUTO',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
