# Generated by Django 4.1.2 on 2022-11-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0003_pedidos_carrinho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='STATUS_CARRINHO',
            field=models.CharField(choices=[('Pedido Realizado', 'Pedido Realizado'), ('Pedido Confirmado', 'Pedido Confirmado')], default='Pedido Realizado', max_length=40),
        ),
    ]
