# Generated by Django 4.1.3 on 2022-11-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0003_remove_produto_created_by_alter_produto_nome_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='VALOR',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
