# Generated by Django 4.1.3 on 2022-11-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0004_alter_produto_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='NOME_CARRINHO',
        ),
    ]
