# Generated by Django 4.1.3 on 2022-11-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0008_alter_carrinho_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='ID_PRODUTO',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='ID_PRODUTO',
            field=models.ManyToManyField(to='Produtos.produto'),
        ),
    ]
