# Generated by Django 4.1.3 on 2022-11-15 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0010_remove_carrinho_quantidade_remove_carrinho_sub_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='ID_PRODUTO',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='ID_PRODUTO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produtos.produto'),
            preserve_default=False,
        ),
    ]
