# Generated by Django 4.1.3 on 2022-11-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0011_remove_carrinho_id_produto_carrinho_id_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='ID_PRODUTO',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='ID_PRODUTO',
            field=models.ManyToManyField(through='Produtos.Produto_Quantidade', to='Produtos.produto'),
        ),
    ]
